version: '3.8'

services:
  runner-app:
    # Inherit all configurations from the base service
    # Login시점 패스워드 입력 필요!
    stdin_open: true # 중요!
    tty: true        # 중요!
    extends:
      file: docker-compose.base.yml
      service: app_base_service
    volumes:
      # 호스트의 경로:컨테이너 내부의 경로
      - ./session:/app/session
      - .:/app  # 현재 폴더(.)를 컨테이너의 /app 폴더와 연결
    # Override/add configurations specific to Telegram Bot production
    container_name: telegram_bot_prod

    # [핵심 추가] 이 줄을 추가하세요!
    env_file:
      - .env

    # Command to run main.py, which will then run indefinitely due to asyncio.run and run_until_disconnected
    command: ["python", "main.py"]
    restart: always # Ensure the container restarts automatically if it stops or the daemon crashes
    # No ports are exposed by default as this is a bot, not a web service.

# Inherit networks and volumes from the base file
networks:
  runner_network:
    driver: bridge

volumes:
  telegram_session_data:
    driver: local
  telegram_downloads_data:
    driver: local
